/**
 * Export name for a brand pack generated by scripts/import-netbox-devices.ts.
 *
 * Lowercases the vendor and drops every non-alphanumeric character, so
 * "TP-Link" becomes "tplinkDevices" (the existing export name) and "D-Link"
 * becomes "dlinkDevices" rather than the invalid "d-linkDevices". A leading
 * digit gets a "_" prefix. The brand pack file name is derived separately.
 */
export function brandPackArrayName(vendor: string): string {
  const base = vendor.toLowerCase().replace(/[^a-z0-9]/g, "");
  if (base === "") {
    throw new Error(
      `Vendor "${vendor}" has no letters or digits to build an identifier from`,
    );
  }
  const prefix = /^[0-9]/.test(base) ? "_" : "";
  return `${prefix}${base}Devices`;
}
