/**
 * Export name for a brand pack generated by scripts/import-netbox-devices.ts.
 *
 * Lowercases the vendor and drops every character other than letters, digits
 * and "_", so "TP-Link" becomes "tplinkDevices" (the existing export name) and
 * "D-Link" becomes "dlinkDevices" rather than the invalid "d-linkDevices". A
 * leading digit gets a "_" prefix. Distinct vendors can collide ("A-B" and
 * "AB"), so the importer checks new names against existing packs. The brand
 * pack file name is derived separately.
 */
export function brandPackArrayName(vendor: string): string {
  const base = vendor.toLowerCase().replace(/[^a-z0-9_]/g, "");
  if (base === "") {
    throw new Error(
      `Vendor "${vendor}" has no letters, digits or "_" to build an identifier from`,
    );
  }
  const prefix = /^[0-9]/.test(base) ? "_" : "";
  return `${prefix}${base}Devices`;
}
